homepage:
    path:     /
    defaults: { _controller: BabyAdvisorBundle:Home:index }

favoris:
    path:     /favoris
    defaults: { _controller: BabyAdvisorBundle:Favoris:index }

profil:
    path:     /profil
    defaults: { _controller: BabyAdvisorBundle:Profil:index }    

membres:
    path:     /membres
    defaults: { _controller: BabyAdvisorBundle:Membres:index }    

admin_suppresion:
    path:     /adminSuppresion
    defaults: { _controller: BabyAdvisorBundle:Admin:confirmation }  

recherche:
    path:     /recherche
    defaults: { _controller: BabyAdvisorBundle:Home:recherche }

signalement:
    path:     /signalement
    defaults: { _controller: BabyAdvisorBundle:Home:signaler }    

view_article:
    path:     /article/{id}
    defaults: { _controller: BabyAdvisorBundle:Home:viewArticles }

ajouter_article:
    path:     /ajouter_article
    defaults: { _controller: BabyAdvisorBundle:Home:ajouterArticle }

activities:
    path:     /activites
    defaults: { _controller: BabyAdvisorBundle:Home:viewActivities }
