homepage:
    path:     /
    defaults: { _controller: BabyAdvisorBundle:Home:index }

favoris:
    path:     /favoris
    defaults: { _controller: BabyAdvisorBundle:Favoris:index }

profil:
    path:     /profil
    defaults: { _controller: BabyAdvisorBundle:Profil:index }    

membres:
    path:     /membres
    defaults: { _controller: BabyAdvisorBundle:Membres:index }    

admin_suppresion:
    path:     /adminSuppresion
    defaults: { _controller: BabyAdvisorBundle:Admin:confirmation }  

recherche:
    path:     /recherche
    defaults: { _controller: BabyAdvisorBundle:Home:recherche }

view_article:
    path:     /article/{id}
    defaults: { _controller: BabyAdvisorBundle:Home:view }