homepage:
    path:     /
    defaults: { _controller: BabyAdvisorBundle:Home:index }

favoris:
    path:     /favoris
    defaults: { _controller: BabyAdvisorBundle:Favoris:index }

profil:
    path:     /profil
    defaults: { _controller: BabyAdvisorBundle:Profil:index }    

membres:
    path:     /membres
    defaults: { _controller: BabyAdvisorBundle:Membres:index }    

admin_suppresion:
    path:     /adminSuppresion/{type}/{id}
    defaults: { _controller: BabyAdvisorBundle:Admin:supprimer }

admin_annuler:
    path:     /adminAnnuler/{type}/{id}
    defaults: { _controller: BabyAdvisorBundle:Admin:annuler }     

recherche:
    path:     /recherche
    defaults: { _controller: BabyAdvisorBundle:Recherche:index }

signaler_article:
    path:     /signaler_article/{idArticle}
    defaults: { _controller: BabyAdvisorBundle:Home:signalerArticle }

signaler_commentaire:
    path:     /signaler_commentaire/{idCommentaire}
    defaults: { _controller: BabyAdvisorBundle:Home:signalerCommentaire }         

view_article:
    path:     /article/{id}
    defaults: { _controller: BabyAdvisorBundle:Home:viewArticles }

ajouter_article:
    path:     /ajouter_article
    defaults: { _controller: BabyAdvisorBundle:Home:ajouterArticle }

activities:
    path:     /activites
    defaults: { _controller: BabyAdvisorBundle:Home:viewActivities }

noter_article:
    path:     /noter_article/{idArticle}
    defaults: { _controller: BabyAdvisorBundle:Home:noterArticle }  

commenter_article:
    path:     /commenter_article/{idArticle}
    defaults: { _controller: BabyAdvisorBundle:Home:commenterArticle }

modifier_commentaire:
    path:     /modifier_commentaire/{idArticle}/{idCommentaire}
    defaults: { _controller: BabyAdvisorBundle:Home:modifierCommentaire }   

voir_commentaire:
    path:     /voir_commentaire/{idCommentaire}
    defaults: { _controller: BabyAdvisorBundle:Admin:voirCommentaire }     

modifier_article:
    path:     /modifier_article/{idArticle}
    defaults: { _controller: BabyAdvisorBundle:Home:modifierArticle }