baby_advisor:
    resource: "@BabyAdvisorBundle/Resources/config/routing.yml"

user:
    resource: "@UserBundle/Resources/config/routing.yml"

connexion:
    resource: "@ConnexionBundle/Resources/config/routing.yml"
