<?php
namespace BabyAdvisorBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * FolderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Centre_interetRepository extends EntityRepository
{

    public function findCentreInteretbyId($ids)
    {
        $age2 = $this->createQueryBuilder('C')
                ->select('C')
                ->where('C.id in ('.$ids.')');
                 
        return $age2->getquery()->getResult();
    }
}