<?php
namespace BabyAdvisorBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * FolderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Tranche_ageRepository extends EntityRepository
{
	public function findTrancheAgebyId($ids)
    {
        $query = $this->createQueryBuilder('T')
                ->select('T')
                ->where('T.id = :id')
                ->setParameter(':id', $ids);
        return $query->getquery()->getResult();
    }

    /*public function filterResult($value='')
    {
    	
    }*/
}