<?php
namespace BabyAdvisorBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * FolderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Tranche_ageRepository extends EntityRepository
{
    public function findTrancheAgebyId($ids)
    {
        $age2 = $this->createQueryBuilder('T')
                ->select('T')
                ->where('T.id in ('.$ids.')');
                 
        return $age2->getquery()->getResult();
    }
}