<?php
namespace BabyAdvisorBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * FolderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Tranche_ageRepository extends EntityRepository
{
	public function findTopArticle($nb)
    {
        $query = $this->createQueryBuilder('A')
			->select('A')
			->join('A.Notes', 'N')
			->addSelect('N')
			->orderBy('N.MoyGen');
        /*$this->getEntityManager()
            ->createQuery(
                "SELECT a FROM Article a JOIN a.Note n ORDER BY n.moy_en ASC"
            );*/
        $query->setMaxResults($nb);
        return $query->getQuery()->getResult();
    }

    public function findTrancheAgebyId($ids)
    {
        $age2 = $this->createQueryBuilder('T')
                ->select('T')
                ->where('T.id in ('.$ids.')');
                 
        return $age2->getquery()->getResult();
    }
}